# Generated by Django 6.1.1 on 2026-09-21 22:55

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=20, null=True)),
                ('rut', models.CharField(help_text='Formato: 12345678-9', max_length=12, unique=True)),
                ('fecha_alta', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.OneToOneField(blank=True, help_text='Usuario del sistema (login) asociado a este cliente, si tiene acceso web.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='Cuenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_cuenta', models.CharField(max_length=20, unique=True)),
                ('tipo', models.CharField(choices=[('AHORRO', 'Caja de ahorro'), ('CORRIENTE', 'Cuenta corriente')], default='AHORRO', max_length=10)),
                ('saldo', models.DecimalField(decimal_places=2, default=0, max_digits=12, validators=[django.core.validators.MinValueValidator(0)])),
                ('activa', models.BooleanField(default=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cuentas', to='gestion.cliente')),
            ],
            options={
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Transaccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('DEPOSITO', 'Depósito'), ('EXTRACCION', 'Extracción'), ('TRANSFERENCIA', 'Transferencia')], max_length=15)),
                ('monto', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('descripcion', models.CharField(blank=True, max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('cuenta_origen', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transacciones', to='gestion.cuenta')),
                ('cuentas_relacionadas', models.ManyToManyField(blank=True, help_text='Otras cuentas involucradas (p. ej. cuenta destino en una transferencia).', related_name='transacciones_relacionadas', to='gestion.cuenta')),
            ],
            options={
                'ordering': ['-fecha'],
            },
        ),
    ]
